
export const STUDENTS_SEED_DATA = [
  { name: "Lyandra Alves Marques", email: "lyandraalvesmarques@gmail.com", password: "lyaepi@1", school_class: "33.06" },
  { name: "Morgana da Rocha Lopes da Silva", email: "mrochalopessilva@gmail.com", password: "123456", school_class: "33.08" },
  { name: "Letícia Isabel Pereira da Silva", email: "leticiaisabelp.silva18@gmail.com", password: "18092008Let", school_class: "33.01" },
  { name: "Isabela Geovana Fagundes Delazzeri", email: "isabelafagundes734@gmail.com", password: "Isa230309@", school_class: "33.09" },
  { name: "Laura Lohara Monteiro Assunção", email: "lauralohara21@gmail.com", password: "Brunalauraarthur21", school_class: "33.08" },
  { name: "Ana clara Pereira dos Santos Leite", email: "anaclarapeite2023@gmail.com", password: "anaclara2008*", school_class: "33.07" },
  { name: "Ana Beatriz Alves lima", email: "anabeatrizalveslima686@gmail.com", password: "beatriz12", school_class: "33.08" },
  { name: "Anna Júlia Cavalcante Borges", email: "cavalcanteannajulia8@gmail.com", password: "annajuli.12", school_class: "23.03" },
  { name: "Isabella Portilho", email: "isabellaportilhoj@gmail.com", password: "21250117", school_class: "33.02" },
  { name: "Isabella Vitoria Araujo Silva", email: "isabelaaraujoesilva4@gmail.com", password: "Baguxu1a", school_class: "23.02" },
  { name: "Ana Luisa Brandão", email: "analuisarodriguesb@gmail.com", password: "Analu3476", school_class: "33.07" },
  { name: "Lara Carvalho de Oliveira", email: "larajapinha27@gmail.com", password: "Lar@27", school_class: "33.09" },
  { name: "Iasmin rosa celestino", email: "celestino.iasrc07@gmail.com", password: "01051218", school_class: "33.04" },
  { name: "Victor Emanoel De Souza Almeida", email: "victor.cpx.trem@gmail.com", password: "18022009 V", school_class: "33.05" },
  { name: "Wanessa Guedes Narciso", email: "wanessaguedesnarciso09@gmail.com", password: "Luaaa009.", school_class: "33.02" },
  { name: "D’Ávila Cristina Parentes dos Santos", email: "davilaparentes@gmail.com", password: "parentes09", school_class: "33.04" },
  { name: "Ezequiel Pereira Maia", email: "maiaezequiel684@gmail.com", password: "22072008Ez.", school_class: "33.06" },
  { name: "Bruna Clay Silva De Jesus Soares", email: "klaybrunad@icloud.com", password: "klay1327", school_class: "33.03" },
  { name: "Nayra", email: "nayra4672@gmail.com", password: "1234", school_class: "23.01" },
  { name: "Isabelly Cecilia", email: "isasousa1805@icloud.com", password: "isabelly18", school_class: "23.02" },
  { name: "CAUA OLIVEIRA DA LUZ ALENCAR", email: "cauaoliveiraa174@gmail.com", password: "571314", school_class: "33.04" },
  { name: "João Pedro Oliveira Alves", email: "jpkff2022@icloud.com", password: "27/09Mae", school_class: "33.05" },
  { name: "Wellika Vitoria De Souza Nunes", email: "wellikavit@icloud.com", password: "Wellika07", school_class: "33.04" },
  { name: "Natalia Costa Fernandes", email: "costafernandesnatalia2@gmail.com", password: "26102009n", school_class: "23.01" },
  { name: "Arthur Fernandes Siqueira", email: "arthurf2215@gmail.com", password: "@Puskasneymar2011", school_class: "23.02" },
  { name: "Geovana Rodrigues vitor Ribeiro", email: "geovanarodriguesvitor@gmail.com", password: "123456", school_class: "23.04" },
  { name: "Matheus da Silva Coutinho", email: "matheusdasilvacoutinho@gmail.com", password: "bela2580", school_class: "33.07" },
  { name: "Kerlon Rodrigues Marques", email: "mcell9175@gmail.com", password: "kerlon103", school_class: "33.02" },
  { name: "Joao Francisco", email: "joaojrrr2009@icloud.com", password: "Larissa0709", school_class: "13.07" },
  { name: "João pedro cerqueira", email: "jp.cerqueiracosta@gmail.com", password: "12junho2008", school_class: "33.06" },
  { name: "Maria Eduarda Louzeiro Nascimento", email: "mlouzeironascimento12@gmail.com", password: "Maria#15", school_class: "33.02" },
  { name: "Lucas Silva Brito", email: "lucas.s.brito127@gmail.com", password: "02112008", school_class: "33.08" },
  { name: "Kaleo Andril de Sousa Vaz", email: "kaleoandril547@gmail.com", password: "13051799", school_class: "33.06" },
  { name: "Calebe Almeida de Araújo", email: "calebe.a.araujo@aluno.senai.br", password: "PET2DZ8W", school_class: "13.06" },
  { name: "Anna Celha Estevão Pereira", email: "annacelha456@gmail.com", password: "120126", school_class: "33.02" },
  { name: "Helena da Silva Martins de Castro", email: "perolasdehelena@gmail.com", password: "pazhelena", school_class: "33.01" },
  { name: "Beatriz Gouvêa Martins", email: "beatrizmartons110@gmail.com", password: "Bia010709", school_class: "23.04" },
  { name: "Mariana Lima do Nascimento", email: "dayananascimento.ascom@gmail.com", password: "Mari@1304", school_class: "23.05" },
  { name: "Ester Oliveira", email: "esuterusama15@gmail.com", password: "Niju", school_class: "23.05" },
  { name: "Sammy dos santos Ferreira", email: "sammysf025@gmail.com", password: "teste123-2014", school_class: "33.04" },
  { name: "Heitor Sardinha", email: "heitor.sardinha64285@gmail.com", password: "heitor1411", school_class: "33.09" },
  { name: "Isadora gomes silva", email: "isadorapgomes@icloud.com", password: "isa4026", school_class: "33.03" },
  { name: "Krishna Weslen dos santos faustino", email: "krishinawf@gmail.com", password: "17112009", school_class: "23.03" },
  { name: "Larissa Neiva Dos Santos", email: "larissaneivadossantos@gmail.com", password: "EhCL231@", school_class: "23.02" },
  { name: "Arthur Almeida Alves", email: "arthuralmeidaalvespmw@gmail.com", password: "arthur02092009", school_class: "23.01" },
  { name: "Natanael Gomes Dias", email: "nataneldias974@gmail.com", password: "senha", school_class: "23.03" },
  { name: "Júlia Victoria da Silva Nobre", email: "juliavictoriadasilvanobre@gmail.com", password: "241316", school_class: "23.02" },
  { name: "Geovana dos Santos Araújo", email: "gs3543310@gmail.com", password: "@Geovanaofc02.", school_class: "33.02" },
  { name: "João Eduardo Rodrigues Rodolfo", email: "jrodriguesrodolfo644@gmail.com", password: "joao123hhJ", school_class: "23.03" },
  { name: "Samyra Silva Santos", email: "samyrasantos0506@gmail.com", password: "20092008", school_class: "23.04" },
  { name: "Vivian gonzaga maia", email: "viviangonzaga@gmail.com", password: "92447868@vivian", school_class: "23.04" },
  { name: "Alicia Irene Braga Da silva", email: "bragaaliciairene@gmail.com", password: "1403209b", school_class: "23.05" },
  { name: "Kallyca Rocha", email: "geruskarochak@gmail.com", password: "Kgrocha13", school_class: "33.05" },
  { name: "Vitória stefane", email: "vitoriastefane2010@gmail.com", password: "20100220", school_class: "23.02" },
  { name: "Marco Antônio Ribeiro Spegiorin", email: "marcoaspegiorin@gmail.com", password: "22143021", school_class: "33.04" },
  { name: "Emanuelli Botelho de Morais", email: "emanuellibotelhosm14@gmail.com", password: "Manu1411&", school_class: "33.06" },
  { name: "Bruno gabriel alencar mendes", email: "brunogab0707@gmail.com", password: "brunin07", school_class: "13.01" },
  { name: "Yasmin Melo Jadão Almeida", email: "yasminmeloja@gmail.com", password: "Mmk03022009@", school_class: "33.02" },
  { name: "Maria Eduarda de souza e silva", email: "marcosalessandro0814@gmail.com", password: "Cenxyf-wahvo2-wosvor", school_class: "13.07" },
  { name: "Ana Clara Rodrigues Sousa", email: "aclara.rodriguessousa@gmail.com", password: "ars276415", school_class: "23.06" },
  { name: "Maria Vitória Teixeira de souza", email: "mariavitoriateixeiradesouza6@gmail.com", password: "12032009", school_class: "33.07" },
  { name: "Arthur Alves da Silva", email: "alvesarthuralvesdasilva084@gmail.com", password: "arthur123", school_class: "23.01" },
  { name: "Julio Cesar Ferreira Rodrigues", email: "juliocfrodrigues5@gmail.com", password: "123456", school_class: "23.02" },
  { name: "Kauane de Oliveira Ribeiro da Silva", email: "aneribeiro446@gmail.com", password: "05Ane2009", school_class: "33.01" },
  { name: "Matheus Da Silva Coutinho", email: "matheusdasilvacoutinho405@gmail.com", password: "Bela2580", school_class: "33.07" },
  { name: "Rosa linda", email: "teixeirarosalinda99@gmail.com", password: "rosacostarf", school_class: "33.08" },
  { name: "Luyz Fernando Alves de Sousa", email: "luyzfernandoalvesdesousa@gmail.com", password: "09092010", school_class: "23.02" },
  { name: "Kélyta Marinho Silva", email: "kelytamarinho10@gmail.com", password: "kelyta2008", school_class: "33.02" },
  { name: "Lucas P. Dantas", email: "lucaspdantas2008@gmail.com", password: "1201103", school_class: "33.04" },
  { name: "Kamilly Martins Lopes", email: "kamillymartinslopes479@gmail.com", password: "K21a22k26", school_class: "33.01" },
  { name: "Samira Pereira da Silva", email: "samirapdasilva@gmail.com", password: "03052008", school_class: "33.01" },
  { name: "Camile Cavalcante Ribeiro", email: "millieyxxx12@gmail.com", password: "Milliey90@", school_class: "33.02" },
  { name: "Ana Clara Domingues Alves da Silva", email: "wwiltonjunior4612@gmail.com", password: "anaHevellyn@22", school_class: "23.06" },
  { name: "Larissa thayla", email: "larissathaylaa@gmail.com", password: "sezhab-nabfuj-poxrE6", school_class: "13.02" },
  { name: "Maria Rita Luz Passos", email: "mariaritaluzpassos@gmail.com", password: "03042009", school_class: "23.01" },
  { name: "Kélyta Marinho", email: "kelytamarinho23@gmail.com", password: "kelyta223", school_class: "33.02" },
  { name: "GUSTAVO FELIPE LIMA RIBEIRO", email: "detetivebatata2@gmail.com", password: "SYBAUgames777", school_class: "13.07" },
  { name: "Gustavo de Sousa da conceição", email: "gugasousa1404@gmail.com", password: "GUGA011", school_class: "13.07" },
  { name: "Rickelme bonfim", email: "rickelmebonfimdossantos@gmail.com", password: "123456", school_class: "33.01" },
  { name: "Keverllyn Sofia A.M", email: "keverllynalves@gmail.com", password: "Km-101214", school_class: "23.02" },
  { name: "Arthur Aragão de Sousa", email: "arthurargao123546@gmail.com", password: "arthur123564", school_class: "33.05" },
  { name: "Warlisson Alves da Silva", email: "warlisson.estudante@gmail.com", password: "warlisson123", school_class: "13.01" },
  { name: "Wemerson Carneiro da Silva", email: "22carneiroton@gmail.com", password: "tom2204", school_class: "33.02" },
  { name: "Pedro henrique brito", email: "phfernandes0708@gmail.com", password: "Ph07082008", school_class: "33.05" },
  { name: "CLEYSE KELY NEVES NOBREGA", email: "cleysek3lly007@gmail.com", password: "pierrot54288", school_class: "23.06" },
  { name: "CAUA OLIVEIRA DA LUZ ALENCAR", email: "cauaoliveiraa174@gmail.com", password: "571314va", school_class: "33.04" },
  { name: "NATHALY FERNANDES DE OLIVEIRA", email: "fernandesaalyynic0@gmail.com", password: "agu4viv4", school_class: "33.07" },
  { name: "Ana Klara Libânia Lima Nobrega", email: "anaklaralima2009@gmail.com", password: "lima1206", school_class: "33.09" },
  { name: "JAQUELINY N SILVA", email: "jacknascimento205@gmail.com", password: "Jack1306@", school_class: "33.01" },
  { name: "Livia Goncalves Santos", email: "liviagoncalves1802@gmail.com", password: "18022011", school_class: "13.04" },
  { name: "Ana Beatriz Barbosa da Rocha", email: "anabeatrizz4689@gmail.com", password: "ABB984670254", school_class: "13.01" },
  { name: "GABRIEL MORAIS DA SILVA", email: "gabrielmorais0978@gmail.com", password: "morais123", school_class: "23.03" },
  { name: "Jefersson Peres Ribeiro", email: "jeferssonperes4@gmail.com", password: "050286", school_class: "33.06" },
  { name: "Jhennifer Borges Moura da Silva", email: "jhenniferr005@gmail.com", password: "wynglesth21", school_class: "23.02" },
  { name: "Lidia Alves", email: "lidiaalvescostaesilva123@gmail.com", password: "123lidia", school_class: "23.04" },
  { name: "Davi gabriel maia marques", email: "davizinhogbrielmaia@gmail.com", password: "davigbriel1214", school_class: "23.05" },
  { name: "Jamily Magualhães", email: "diasjamily2010@gmail.com", password: "123456", school_class: "23.01" },
  { name: "Lady Laura Santiago Barros", email: "ladylaurasantiagobarros63@gmail.com", password: "santiago@2010", school_class: "13.07" },
  { name: "Ysadora Santos Da Cruz", email: "ysadoracruz08@gmail.com", password: "ysa_2008", school_class: "33.07" },
  { name: "Helena Coelho Burgos", email: "helenacoelhoburgos@gmail.com", password: "papelaria@2011", school_class: "13.07" }
];
